### ISSUE TITLE
Error when pressing "Start" on the generator app

### ISSUE THREAD

**Issue by GooberMooms** [matdillen/legendary-generator#82]
When I press start on the generator app it gives out the following error and nothing happens: Problem while computing `..1 = across(everything(), ~replace_na(., 0))`.

**Comment by matdillen** [comment]
Thanks for reporting this. I think it should be fixed now per 22de45356afba3a7b69bb6902241620516abacfc. I didn't have the bug yet as I was still working with an older version of R and older package versions.

**Comment by GooberMooms** [comment]
Works great! Thank you!
